# Generated by Django 5.1.5 on 2025-01-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('feedback_type', models.CharField(choices=[('Food', 'Food'), ('Bed', 'Bed'), ('Staff', 'Staff'), ('Other', 'Other')], max_length=50)),
                ('comment', models.TextField()),
                ('rating', models.PositiveIntegerField()),
            ],
            options={
                'permissions': [('view_own_feedback', 'Can view own feedback')],
            },
        ),
        migrations.CreateModel(
            name='FoodToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_name', models.CharField(max_length=255)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks'), ('Parcel', 'Parcel')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Served', 'Served'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
            ],
            options={
                'permissions': [('view_own_foodtoken', 'Can view own food tokens')],
            },
        ),
    ]
