# Generated by Django 5.1.5 on 2025-01-24 05:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_feedback_options_alter_foodtoken_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, choices=[('LP', 'Loco Pilot'), ('ALP', 'Assistant Loco Pilot'), ('SALP', 'Senior Assistant Loco Pilot'), ('LPG', 'Loco Pilot Goods'), ('SHT', 'Shunter'), ('SSHT', 'Senior Shunter'), ('LPP', 'Loco Pilot Passenger'), ('LPM', 'Loco Pilot Mail'), ('MMAN', 'Motorman'), ('AGR', 'Assistant Guard'), ('SAGR', 'Senior Assistant Guard'), ('GD', 'Guard'), ('SGD', 'Senior Guard'), ('SGDP', 'Senior Guard Passenger'), ('GDM', 'Guard Mail'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        # migrations.AddField(
        #     model_name='customuser',
        #     name='mobile_number',
        #     field=models.CharField(default=1, max_length=15, unique=True),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(max_length=15, default='9999999999'),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='foodtoken',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CrewCheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_train_name', models.CharField(max_length=255)),
                ('outgoing_train_name', models.CharField(blank=True, max_length=255, null=True)),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('rest_clear_time', models.DateTimeField(blank=True, null=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_check_ins', to='core.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('Crew Member', 'Crew Member'), ('Caretaker', 'Caretaker'), ('Contractor', 'Contractor'), ('Crew Controller', 'Crew Controller')], max_length=50)),
                ('designation', models.CharField(blank=True, choices=[('LP', 'Loco Pilot'), ('ALP', 'Assistant Loco Pilot'), ('SALP', 'Senior Assistant Loco Pilot'), ('LPG', 'Loco Pilot Goods'), ('SHT', 'Shunter'), ('SSHT', 'Senior Shunter'), ('LPP', 'Loco Pilot Passenger'), ('LPM', 'Loco Pilot Mail'), ('MMAN', 'Motorman'), ('AGR', 'Assistant Guard'), ('SAGR', 'Senior Assistant Guard'), ('GD', 'Guard'), ('SGD', 'Senior Guard'), ('SGDP', 'Senior Guard Passenger'), ('GDM', 'Guard Mail'), ('Others', 'Others')], max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lobby_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lobby')),
            ],
        ),
    ]
