# Generated by Django 5.1.5 on 2025-01-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_designation_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(default='9999999999', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='mobile_number',
            field=models.CharField(default='9999999999', max_length=15),
        ),
    ]
