# Generated by Django 5.1.5 on 2025-01-24 07:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_registrationrequest_lobby_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, choices=[('LP', 'Loco Pilot'), ('ALP', 'Assistant Loco Pilot'), ('SALP', 'Senior Assistant Loco Pilot'), ('LPG', 'Loco Pilot Goods'), ('SHT', 'Shunter'), ('SSHT', 'Senior Shunter'), ('LPP', 'Loco Pilot Passenger'), ('LPM', 'Loco Pilot Mail'), ('MMAN', 'Motorman'), ('AGR', 'Assistant Guard'), ('SAGR', 'Senior Assistant Guard'), ('GD', 'Guard'), ('SGD', 'Senior Guard'), ('SGDP', 'Guard Passenger'), ('GDM', 'Guard Mail'), ('Others', 'Others')], help_text='Designation for Crew Members', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number for the user. Must be unique.', max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Crew Member', 'Crew Member'), ('Crew Controller', 'Crew Controller'), ('Caretaker', 'Caretaker'), ('Contractor', 'Contractor')], max_length=50)),
                ('designation', models.CharField(blank=True, choices=[('LP', 'Loco Pilot'), ('ALP', 'Assistant Loco Pilot'), ('SALP', 'Senior Assistant Loco Pilot'), ('LPG', 'Loco Pilot Goods'), ('SHT', 'Shunter'), ('SSHT', 'Senior Shunter'), ('LPP', 'Loco Pilot Passenger'), ('LPM', 'Loco Pilot Mail'), ('MMAN', 'Motorman'), ('AGR', 'Assistant Guard'), ('SAGR', 'Senior Assistant Guard'), ('GD', 'Guard'), ('SGD', 'Senior Guard'), ('SGDP', 'Guard Passenger'), ('GDM', 'Guard Mail'), ('Others', 'Others')], help_text='Designation is required for Crew Members', max_length=20, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
