# Generated by Django 5.1.5 on 2025-01-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customuser_designation_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='lobby_code',
            field=models.CharField(help_text='Lobby Code', max_length=10, null=True, unique=True),
        ),
    ]
