# Generated by Django 5.1.5 on 2025-01-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lobby_lobby_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='lobby_code',
            field=models.CharField(help_text='Lobby Code', max_length=10, unique=True),
        ),
    ]
