# Generated by Django 5.1.5 on 2025-01-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_customuser_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='number',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
    ]
