# Generated by Django 5.1.5 on 2025-02-01 05:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_bed_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_name', models.CharField(max_length=255)),
                ('bed_number', models.CharField(max_length=10)),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bed')),
                ('checked_in_lobby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_lobby', to='core.lobby')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
                ('crew_hq_lobby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_hq_lobby', to='core.lobby')),
            ],
        ),
    ]
